#!/usr/bin/python

import sys
import socket

# Campo
CLIREQ = '01'

# Servent contato
enderecoServent = sys.argv[1]
ip, port = enderecoServent.split(":")

UDP_IP = ip
UDP_PORT = int(port)

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP

# Input do usuario
MESSAGE = raw_input()
mensagemFinal = CLIREQ + MESSAGE
sock.sendto(mensagemFinal, (UDP_IP, UDP_PORT))

# Recebendo resposta do Servent
sock.settimeout(4)
data, addr = sock.recvfrom(1024)
print "received message:", data

