#!/usr/bin/python

import sys
import socket
import struct

# Campo
CLIREQ = 1

# Servent contato
enderecoServent = sys.argv[1]
ip, port = enderecoServent.split(":")

UDP_IP = ip
UDP_PORT = int(port)

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP

# Input do usuario
MESSAGE = raw_input()
mensagemFinal = struct.pack('>H', CLIREQ) + MESSAGE
sock.sendto(mensagemFinal, (UDP_IP, UDP_PORT))

# Aguardando resposta
try:
  sock.settimeout(4)
  data, addr = sock.recvfrom(1024)
  resposta = ' '.join(data.split()[1:])
  chave = data.split()[0]
  print "Resposta:", chave[2:], resposta 

# Reenvia
except:
  sock.sendto(mensagemFinal, (UDP_IP, UDP_PORT))
  # Aguarda 4s por outras respostas
  while True:
    sock.settimeout(4)
    data, addr = sock.recvfrom(1024)
    resposta = ' '.join(data.split()[1:])
    chave = data.split()[0]
    print "Resposta: ",chave[2:], resposta
