#!/usr/bin/python

import sys
import socket

# Campo
CLIREQ = '01'
QUERY = '02'
TTL = '03'

# Recebendo porta
PORT = int(sys.argv[1])

# Arquivo
arquivo = sys.argv[2]

# Contador
contMSG = 0

# IP e porta 
UDP_IP = socket.gethostbyname(socket.gethostname())
UDP_PORT = PORT
print UDP_IP

# Socket UDP
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))

# Array de vizinhos
arrayVizinhos = []

KV = open(arquivo,'r') 
for line in KV: 
  arrayVizinhos.append(line.strip('\n'))

for i in arrayVizinhos:
  print i

# Aguardando mensagens
while True:
  data, addr = sock.recvfrom(1024) 
  print "received message:", data
  print addr
  print data[0:2]
  if data[0:2] == CLIREQ:
    # Enviando mensagem ao client
    print "enviando ", data[2:]
    sock.sendto(data, addr)
    print "CLIREQ"
    # Montar QUERY
    contMSG = contMSG + 1
    tratarIP = socket.inet_aton(addr[0])
    contador = str('{:04d}'.format(contMSG))
    portaString = str('{:04d}'.format(addr[1]))
    query = QUERY + TTL + tratarIP + portaString + contador + data[2:]
    print query
    print "enviando aos vizinhos"
    for i in arrayVizinhos:
      #print i.split(':')[0], i.split(':')[1]
      ipVizinho = i.split(':')[0]
      portaVizinho = int(i.split(':')[1])
      sock.sendto(query, (ipVizinho,portaVizinho))
  if data[0:2] == QUERY:
    print "bla"

  
